In [1]:
import numpy as np

In [8]:
import numpy as np
def no_zeros(arrayInput):
    ## TODO: This function should return True if 
    ## numpy array arrayInput does not contain any zero
    ## and will return False otherwise.
    ## Implement this function using ONLY numpy methods
    ## Sample input: [1,2,3,4,5,6,0] Sample Output: False
     
    #  np.where(np.any(arrayInput)==0)
    #  return atleast_1d(np.any(arrayInput)==0).nonzero()
    return np.all(arrayInput != 0)  #np.all test all array elements along a given axis evaluate to True or false
arr1 = np.array([1, 2, 3, 4,0])
print(no_zeros(arr1))



False


In [10]:
def linearly_distributed(n, min, max):
    ## TODO: This function should return a numpy array of 
    ## length n with equally spaced elements from 
    ## min (inclusive) to max (exclusive)
    ## Implement this function using ONLY numpy methods
    ## Sample input: (4,0,100) sample output [0,33,66, 99]
     return np.linspace(min,max,n, endpoint=False, dtype=int )
    
arr1= np.array([4,0,100])
min_arr1=np.min(arr1)
max_arr1=np.max(arr1)
array_No=4
print(linearly_distributed(array_No,min_arr1,max_arr1))


[ 0 25 50 75]


In [17]:

def two_dimensions(n):
    ## TODO: This function should create a 2d Array of shape n*n
    ## Where the borders of the array are ones
    ## all other elements are zero
    ## Implement this function using ONLY numpy methods
    ## Sample input 3
    ## sample output [[1,1,1],[1,0,1],[1,1,1]]
    my_array=np.ones((n,n),dtype=int)         #creating array full with ones
    
    my_array[1:-1,1:-1] =0                         #change the elemets from second row(1)to befor last 
                                                   #and second culom to before last to one
    return my_array
array_dimention=5
print(two_dimensions(array_dimention))

    

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [2]:
import numpy as np
def create_array(n,min,max):
    ## TODO: This function should return a numpy array of 
    ## length n with random elements from 
    ## min (inclusive) to max (exclusive)
    ## Implement this function using ONLY numpy methods 
    ## USE np.random.rand for generating the numbers 
    ## Sample Input (10,0,10) sample output(0,2,2,3,1,5,9,7,8,3)
   return np.random.randint(min,max,size=n)       #Returning random integers from low (inclusive) to high (exclusive)
   
minimum_no=0
maximun_no=10
lenght=10
print(create_array(lenght,minimum_no,maximun_no))

[0 8 2 6 1 0 2 1 0 9]


In [6]:
def random_generation(n,min,max):
    ## TODO: Write a function that takes as an input
    ## Dimension of 2d Array n, min and max
    ## Generate an n*n array with random numbers between
    ## min and max inclusive
    ## Such that no element is duplicated
    ## return numpy array
    ## Implement this function using ONLY numpy methods
    ## Sample Input: random_generation(3,0,12) --> [[4,2,6],[1,5,11],[10, 3,9]]
    
    
    a=np.random.choice(np.arange(min,max),size=n*n,replace=False)
    return a.reshape((n, n))
  
     
minimum_no=0
maximun_no=25
lenght=5
print(random_generation(lenght,minimum_no,maximun_no))

[[14  2 18 16 23]
 [22 13  6 21  9]
 [ 1  3 24 19 10]
 [11 17  0  5 20]
 [ 4 15  8 12  7]]
